### PR TITLE
Correct common name of example server certificate

### PR DESCRIPTION
**Pull request by utsavm9**
Resolves https://github.com/boostorg/beast/issues/2266.

Now, testing the async-ssl server with `curl https://localhost:8000/ --cacert cert.pem` will not give a relatively cryptic error message like:
```
curl: (60) SSL: unable to obtain common name from peer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html
```
but would hint the developer to create their own certificate by showing a message like:
```
curl: (60) SSL: certificate subject name 'www.example.com' does not match target host name 'localhost'
```

## Testing
Compiled and ran the async-ssl server example code in a seperate CMake project. Could not figure out how to build the project in the `beast` repo as is, so I have also not run any tests locally.

### CODE REVIEW

**Comment by utsavm9** [comment]
I am guessing the coverage went down because some of the errors do not occur after the change, but I am not sure. Let me know what I can do to increase the coverage, if that is needed in this PR to merge.

**Comment by nancho84** [comment]
[]()

**Comment by madmongo1** [comment]
I'm happy to overlook the coverage "drop". I'll get it merged today

**Comment by vinniefalco** [comment]
@alandefreitas please verify the commit is correct and then merge

**Pull request merged**
