### PR TITLE
Use zlib::Flush::sync instead of zlib::Flush::full, for stream compre…

### PR DESCRIPTION
**Pull request by chreniuc**
…ssion

https://github.com/boostorg/beast/issues/2313

### CODE REVIEW

**Comment by chreniuc** [comment]
I've noticed that this failed, due to lower code coverage. But its a little bit confusing, it shows that the code coverage dropped in [this file](https://app.codecov.io/gh/boostorg/beast/compare/2318/changes)(`include/boost/beast/websocket/impl/read.hpp`). Which was not modified by me, and also that file doesn't use the `deflate()` method that was changed.

**Comment by madmongo1** [comment]
This has passed all tests. Thank you for your valuable contribution. 

I would welcome a suggestion on a test I could implement to prove that this is a fix/improvement.

R

**Comment by chreniuc** [comment]
The method that I've changed is [this](https://github.com/boostorg/beast/blob/9f2b0ce1db9868b9ec54ebed18bebced53e76782/include/boost/beast/websocket/detail/impl_base.hpp#L83), I tried to find it's related test file, but I only found [this](https://github.com/boostorg/beast/blob/develop/test/beast/websocket/_detail_impl_base.cpp), which is empty.
 
 I saw that `deflate()` is used in [this file](https://github.com/boostorg/beast/blob/b7344b0d501f23f763a76488826dde8c31f34b5d/include/boost/beast/websocket/impl/write.hpp#L462), when `write_some_op::operator()` is called  or when [write_some](https://github.com/boostorg/beast/blob/b7344b0d501f23f763a76488826dde8c31f34b5d/include/boost/beast/websocket/impl/write.hpp#L608) is called, so I think the test might be done [here](https://github.com/boostorg/beast/blob/develop/test/beast/websocket/write.cpp) somehow.
 
The test that I was thinking about if we were to only test the `deflate()` method:
 - start with `Hello` string
 - call `deflate()`, the resulted string will be 7 bytes or will have this content: `0xf2 0x48 0xcd 0xc9 0xc9 0x07 0x00`
 - call `deflate()` with the same string, and the result will be 5 bytes or will have this content: `0xf2 0x00 0x11 0x00 0x00`
 
 Which means that compressing the same string, results has two different outputs, the second time the size is smaller.
 
A better test would be to test this in the [write_some](https://github.com/boostorg/beast/blob/b7344b0d501f23f763a76488826dde8c31f34b5d/include/boost/beast/websocket/impl/write.hpp#L608) method, because there we can also check that the `client_no_context_takeover` or `server_no_context_takeover` do actually work. So there would be two tests:

**Test 1: Test where the sliding window is not used between writes**

 - start with `Hello` string, role(server or client), `server_no_context_takeover` or `client_no_context_takeover` set to `true`(based on the role)
 - call `write_some` with that string, the resulted string will be 7 bytes or will have this content: `0xf2 0x48 0xcd 0xc9 0xc9 0x07 0x00`
 - call `write_some`  with the same string, and the result will be 7 bytes or will have this content: `0xf2 0x48 0xcd 0xc9 0xc9 0x07 0x00`

This is because `server_no_context_takeover` or `client_no_context_takeover` were set to true, so when [this](https://github.com/boostorg/beast/blob/b7344b0d501f23f763a76488826dde8c31f34b5d/include/boost/beast/websocket/impl/write.hpp#L685) is called, it resets the compression stream, [here](https://github.com/boostorg/beast/blob/b7344b0d501f23f763a76488826dde8c31f34b5d/include/boost/beast/websocket/detail/impl_base.hpp#L155).

**Test 2: Test where the sliding window is used between writes**

 - start with `Hello` string, role(server or client), `server_no_context_takeover` or `client_no_context_takeover` set to `false`(based on the role)
 - call `write_some` with that string, the resulted string will be 7 bytes or will have this content: `0xf2 0x48 0xcd 0xc9 0xc9 0x07 0x00`
 - call `write_some`  with the same string, and the result will be 5 bytes or will have this content: `0xf2 0x00 0x11 0x00 0x00`

This is because `server_no_context_takeover` or `client_no_context_takeover` were set to false, so when [this](https://github.com/boostorg/beast/blob/b7344b0d501f23f763a76488826dde8c31f34b5d/include/boost/beast/websocket/impl/write.hpp#L685) is called, it won't reset the compression stream, [here](https://github.com/boostorg/beast/blob/b7344b0d501f23f763a76488826dde8c31f34b5d/include/boost/beast/websocket/detail/impl_base.hpp#L155).

Hope this helps a little.

**Comment by vinniefalco** [comment]
The coverage report is a tiny bit flaky, don't worry too much about it

**Pull request closed without merging**
