### PR TITLE
Refactor CMakeLists

### PR DESCRIPTION
**Pull request by ashtum**

### CODE REVIEW

**Comment by vinniefalco** [comment]
This is looking great now. If you could please change the README.md to include updated instructions for building the 32 bit and the 64 bit solutions. I used:

```
cmake -G "Visual Studio 17 2022" -A x64 -B bin64 -DBUILD_TESTING=ON -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE="C:/Users/vinnie/src/boost/libs/http_io/cmake/toolchains/msvc.cmake"
```

**Comment by ashtum** [comment]
> This is looking great now. If you could please change the README.md to include updated instructions for building the 32 bit and the 64 bit solutions. I used:
> 
> ```
> cmake -G "Visual Studio 17 2022" -A x64 -B bin64 -DBUILD_TESTING=ON -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE="C:/Users/vinnie/src/boost/libs/http_io/cmake/toolchains/msvc.cmake"
> ```

There's no need to set `BUILD_TESTING` anymore. When Boost.Beast is the root project, it includes `CTest`, which automatically sets `BUILD_TESTING`:

```cpp
if (BOOST_BEAST_IS_ROOT)
    include(CTest)
endif ()
option(BOOST_BEAST_BUILD_TESTS "Build boost::beast tests" ${BUILD_TESTING})
```

**Comment by vinniefalco** [comment]
Don't tell me that just edit the command line as you see fit, and insert it into the README

**Comment by ashtum** [comment]
> Don't tell me that just edit the command line as you see fit, and insert it into the README

It's already in the README, do you want me to change `C:/boost/libs/beast/cmake/toolchains/msvc.cmake` to `C:/Users/vinnie/src/boost/libs/http_io/cmake/toolchains/msvc.cmake`?

**Comment by vinniefalco** [comment]
There is no file "C:/boost/libs/beast/cmake/toolchains/msvc.cmake". You could refer to this path instead:
https://github.com/boostorg/url/blob/develop/cmake/toolchains/msvc.cmake

**Pull request merged**
