### PR TITLE
Add multiple content length error

### LINKED ISSUE #2468: HEAD Content-Length parsing is too strict
### Version of Beast

322

### Steps necessary to reproduce the problem

```cpp
         // Send the HTTP request
         ::boost::beast::http::request<::boost::beast::http::empty_body> req(
            ::boost::beast::http::verb::head, state->target, 11);
         req.set(::boost::beast::http::field::host, {state->connection->host.data(), state->connection->host.size()});
         req.prepare_payload();
         OUTCOME_CO_TRY(co_await ::boost::beast::http::async_write(stream, req, make_token()));

         // Read the HTTP response
         ::boost::beast::flat_buffer                                              buffer;
         ::boost::beast::http::response_parser<::boost::beast::http::empty_body> resp_parser(
            ::boost::beast::http::status::unknown, 1);
         ::boost::beast::http::response<::boost::beast::http::empty_body> resp;
         // Apparently this is necessary to make Beast not puke on processing a HEAD response
         resp_parser.skip(true);
         result<size_t> r = co_await ::boost::beast::http::async_read_header(stream, buffer, resp_parser, make_token());
         resp             = resp_parser.release();
```

` ::boost::beast::http::async_read_header()` still returns `error::bad_content_length` if the HEAD response contains a `Content-Length` exceeding the body size (which is zero).

HTTP spec says:

```
   A server MAY send a Content-Length header field in a response to a
   HEAD request ([Section 4.3.2 of [RFC7231]](https://datatracker.ietf.org/doc/html/rfc7231#section-4.3.2)); a server MUST NOT send
   Content-Length in such a response unless its field-value equals the
   decimal number of octets that would have been sent in the payload
   body of a response if the same request had used the GET method.
```

Examples of this occurring in the wild:

```
curl --head https://gohugo.io
HTTP/1.1 200 OK
Age: 60131
Cache-Control: public, max-age=0, must-revalidate
Content-Length: 53138
Content-Type: text/html; charset=UTF-8
Date: Tue, 21 Jun 2022 01:05:11 GMT
Etag: "42b17e0a6eb8d5b945b5609fa701f683-ssl"
Link: </dist/app.bundle.js>; rel=preload; as=script, </dist/main.css>; rel=preload; as=style
Referrer-Policy: origin-when-cross-origin
Server: Netlify
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Nf-Request-Id: 01G63P0HHDCD4X22DGQ87C9HNS
X-Xss-Protection: 1; mode=block


curl --head https://www.nedprod.com
HTTP/1.1 200 OK
Server: nginx/1.21.6
Date: Tue, 21 Jun 2022 17:52:12 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 183275
Last-Modified: Sun, 19 Jun 2022 23:08:02 GMT
Connection: keep-alive
Vary: Accept-Encoding
ETag: "62afac52-2cbeb"
Strict-Transport-Security: max-age=15768000;
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Robots-Tag: none
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
Referrer-Policy: strict-origin
Accept-Ranges: bytes
```

Proposed solution to https://github.com/boostorg/beast/blob/develop/include/boost/beast/http/impl/basic_parser.ipp#L833:

```
            if (existing.has_value())
            {
                if (v != *existing)
                {
                    if(f_ & flagSkipBody)
                    {
                        existing = v;
                    }
                    else
                    {
                        return bad_content_length();
                    }
                }
            }
            else
            {
                existing = v;
            }
```

Potentially related: #2322

**Edit:** Improved proposed solution.

### PR DESCRIPTION
**Pull request by alandefreitas**
fix #2468

### CODE REVIEW

**Comment by alandefreitas** [comment]
@ned14

**Comment by vinniefalco** [comment]
Seems ok. What does @ned14 think?

**Comment by klemens-morgenstern** [comment]
Can this be merged?

**Comment by klemens-morgenstern** [comment]
No objections, so i'll merge.

**Pull request merged**
