### PR TITLE
Consolidate drone configs

### PR DESCRIPTION
**Pull request by sdarwin**
Reduce total number of drone config files. Include more drone tests.

### CODE REVIEW

**Comment by vinniefalco** [comment]
Is this good to go?

**Comment by sdarwin** [comment]
> Is this good to go?

@madmongo1 is welcome to review.  At the time of submitting the PR, all tests had passed, ready to merge: https://drone.cpp.al/boostorg/beast/137

**Comment by madmongo1** [comment]
Yep, happy to accept

**Comment by madmongo1** [comment]
Rebased to develop

**Pull request closed without merging**
