### PR TITLE
Fix writing headers into std::ostream

### PR DESCRIPTION
**Pull request by inetic**

### CODE REVIEW

**Comment by vinniefalco** [comment]
Whoops! I wonder why clang and gcc didn't generate a compile error?

**Comment by vinniefalco** [comment]
Ah, probably because it is a template function and it is not called! I appreciate the pull request.

Just a hint, but if you want this pull request to be even more amazing, consider adding:

* A small test (in test/beast/http/write.cpp) which constructs a message and writes it to a `std::stringstream`, checks the result.

**Comment by vinniefalco** [comment]
Your commit is part of version 118: https://github.com/boostorg/beast/pull/794

**Comment by inetic** [comment]
Thanks. You're right, a test for it would be nice. I'll try to add one when time permits.

**Comment by vinniefalco** [comment]
@inetic I already added one, it was easy - thanks!

**Comment by vinniefalco** [comment]
These examples also have an extraneous strand for listener:

* http-server-async-ssl
* websocket-server-async
* websocket-server-async-ssl

**Comment by vinniefalco** [comment]
Merged, thanks!

**Pull request closed without merging**
