### PR TITLE
Add [issue] tags in release_notes.qbk

### PR DESCRIPTION
**Pull request by madmongo1**

### CODE REVIEW

**Comment by vinniefalco** [comment]
Where's the version tag? Also consider this commit message instead:

> Add issue links in release notes

**Comment by madmongo1** [comment]
You mean a git tag? I don’t think we’ve covered this. 
Would you like me to add a v1.73 tag and change the commit message?
After this, I take it one of us merges to master and informs the boost channel?

**Comment by vinniefalco** [comment]
> Would you like me to add a v1.73 tag and change the commit message?

I"m talking about a commit that changes the Beast version number, which should be 290 now.

**Comment by vinniefalco** [comment]
The 2 commits which affect CI need to be squashed into 1

**Pull request closed without merging**
