### PR TITLE
fix asserts, it's possible that we reach code only with 3 symbols

### PR DESCRIPTION
**Pull request by ruz**
This happens when:
* chunked encoding
* body is empty
* chunk has no extensions
* and put calls are really weird

### CODE REVIEW

**Comment by ashtum** [comment]
The minimum valid chunked body is `0\r\n\r\n`, do you what to treat `0\r\n` as a valid body?

**Comment by ruz** [comment]
No, I don't want to. This is a streamed parser, imagine put calls with the following sequence: '0\r\n', '\r' and '\n'. The current code will fail with the assert on the second put as n will be equal to 4.

What I want to do is to correct the assert and make it valid. If flagExpectCRLF is set then n should be >= 5, otherwise 3 is possible and ok. Code that goes after, searches for CRLFCRLF (eom) sequence and correctly returns need_more.

**Comment by ashtum** [comment]
> What I want to do is to correct the assert and make it valid. If flagExpectCRLF is set then n should be >= 5, otherwise 3 is possible and ok. Code that goes after, searches for CRLFCRLF (eom) sequence and correctly returns need_more.

You are correct; the current code returns the error_code `error::need_more`, which expects more data in the next call, which can be as little as one byte. Thank you very much for reporting this and for your PR; I'll add the related test cases and merge this.

@vinniefalco

**Comment by vinniefalco** [comment]
LGTM

**Comment by ruz** [comment]
thanks

**Pull request merged**
