### PR TITLE
Issue/2606

### LINKED ISSUE #2606: completion-less spawn is deprecated.
Just do the right thing.

### PR DESCRIPTION
**Pull request by klemens-morgenstern**
Closes #2606.

### CODE REVIEW

**Comment by vinniefalco** [comment]
This all looks ok

**Comment by vinniefalco** [comment]
something isn't right, this is segfaulting on CI

**Comment by vinniefalco** [comment]
Yes this seems prudent

**Comment by klemens-morgenstern** [comment]
merging, as only the s390x clang failed before.

**Pull request merged**
